[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_hello_world = "DujYufgNvyey7ttDcf6a9uVQbG7nTtVWVKgLn1rZ1MZf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/renzo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
